language: node_js
node_js:
- node
sudo: false
deploy:
  provider: npm
  email: rthaut@gmail.com
  api_key:
    secure: QriGm3NIrcYIHya0tyADJDGsXnQrDGxyzlXYmy8G5FR14/s2Ek/ZvDHQWnIPPMkoYKkI1IjLHj01uFzlw6aXu8Zrrjmkv5SWOygGoIZM1BGKj0IDStDLxTlVDUU+3g6GEXbEWEFE7WsnDHGiyrVqgYvz/Msm6c5ewNys9RmcghR/vH4KdL1SmlYRVwgn43I2TDCkPmnOpmDtrkEWpCGvhwPm+gy5X6SLteBZv+7mTXpdaDnuHR0/2bj6jwir+X5kgvvxQelJDr7wN1oBxPFJSrEO7cmXy+CCVehnvD+BtQqKe85oLXClWHI1jx95qY1As0zPuQymWjgZiifWVmqBHJYqih+kmBUmkFW4C3WQSf6vmesXEN7gzpRiWbEyhN6jXMDWgiKYE0dByTTFnC7rMVCelzZ1HQP2h4kwGJnrv4kCZMpszG1n8/8iBmZ/j1Fw9oj13rZ5TIoryk10+IxMeiOPHrxEroiYzhcu1xU+JilGjZxkVRJc8q+G7H5eB9pLF1OKg6dtl39jTY661jf0QAD6utummhOlFGnpITxGkZw2p8Q3QMaOyOPm2xqRMpYCwK8wVw/bqhLsx4Gsg57dys4FZt6OuosGtBji3UFe7y6QmQSzj8Or/uLImlHgtw/rY0SpyKIIjZ4+vSx5Fe3ZWfDuGDmcYSDbCywo9ia2iCA=
  on:
    tags: true
    repo: rthaut/gulp-browser-i18n-localize
