language: node_js
node_js:
- node
sudo: false
deploy:
  provider: npm
  email: rthaut@gmail.com
  api_key:
    secure: l4BOtflT1iYtOEAElW4+Og8RtqjOsjCMxrjiX+2a9l0CJq4DqcI1YO49ks9wtup5nz2EXlCQ75mIHYx6nA7YBt3slG/zB9HvBEQR/d8Zo7ZnvYdBixoSFahhmpYoe+bV0ADbrZOgxu9voctc4gcGsy2GQK/W7MkS/tdjpK1w3qRwWJkMrVi39Y9seR4uLpjtBvuCqRHmr228Zr3Hpr+pXWxMDWvjgaPLjdmz9aMdr7vjNvXmOSiAPBzxoalsVX+XWpwfMeZiFcHbYB9dPGZEzA8gmnf0LzT6ZtDqK/wykKgGPYBILfQzY101JjMW83/wz5ZJNIU0jbJVY3mDKm56XyFdRjokbCI3DLc2H0Nmq5nCy1F9KYFfFxo621/dPkeh8a7VlJmupptjPgMWFReHxG4yc17Q0kvgnwgDamYMLWQ72jzb1izHHvE7Qu2AeZlLo2YQY8Ik4LhcXj9Z4oCShpOdJmnNOaSNEjkHpgMQlggBjufjawskQT1SMJKk4fHW1hgBqteyMaJNcra5y6s8k1BtsOnsmP+qt24J0TQ2hx+N5rHAicIJ/XswsS+e4fCOeV8cplBi+SDAzcxBFqS5HFI0qYltt1078R8thQdCXOMMQnn3XNX6wTfl+D4go/vXui6vaBWdOZQ+ln2h9WfJg+WnuPoWURRXGopHxIkROd4=
  on:
    tags: true
    repo: rthaut/gulp-browser-i18n-localize
